version: '3'
services:
  db:
    image: postgres:10
    restart: always
    volumes:
      - ./.persistence/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./.persistence/redis:/data

  web:
    build: .
    restart: always
    volumes:
      - .:/bandit
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - db
      - redis
    environment:
      RACK_ENV: production
